### ISSUE TITLE
How can we get more control over styling the glider-track?

### ISSUE THREAD

**Issue by prathamesh-gharat** [kevinfarrugia/react-glider#120]
Hi, I am trying to figure out a good way to apply a style on the glider track. For example, how to apply a `gap: 12px` between the slide items and `justify-content: center` to align the items to the centre of the screen if there are less number of items than the screen allows; I cannot figure out a non-hacky way of doing this in react.

My current implementation involves giving the slider a unique class and then applying a `gap: 12px` and `justify-content: center` on the `.glider-track` under the unique class.

**Comment by kevinfarrugia** [comment]
You are able to add your own custom styling to the `glider-track` by using the `skipTrack` property. If `skipTrack` is true, it will assume the first child of the `<Glider>` to be the track and add the `glider-track` class name to it. This allows you to add your own `className`, `style` or semantic HTML.

**Example**
```
      <Glider slidesToShow={3} skipTrack>
        <div className="custom-track">
          <div className="slide">
            <span>1</span>
          </div>
          <div className="slide">
            <span>2</span>
          </div>
        </div>
      </Glider>
```
