### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by callum-gander** [kevinfarrugia/react-glider#136]
In the original package, this is an option (see https://github.com/glidejs/glide/issues/514). Is this available with this wrapper?

**Comment by kevinfarrugia** [comment]
Will look into it. Might require a minor change.

**Comment by kevinfarrugia** [comment]
@callum-gander The original package is [gliderjs](https://github.com/NickPiscitelli/Glider.js/) which doesn't support infinite scrolling.

**Comment by haveamission** [comment]
@kevinfarrugia Are you sure about that?

https://github.com/glidejs/glide/issues/514

**Comment by kevinfarrugia** [comment]
Demo: https://react-glider.vercel.app/#autoplay_glider
