### ISSUE TITLE
Possible to programmatically navigate to a slide via code?

### ISSUE THREAD

**Issue by haveamission** [kevinfarrugia/react-glider#142]
Is it possible to have an external event that lets a user go to a specific slide?

Something like the parent library's:

`scrollTo`

function

**Comment by kevinfarrugia** [comment]
It can be done using the `scrollItem` method.

Check the demo: https://react-glider.vercel.app/#ref_exposes_glider

```jsx
const gliderRef = React.useRef < GliderMethods > null;

return (
  <button
    type="button"
    onClick={() => {
      const random = Math.floor(Math.random() * 12);

      gliderRef.current?.scrollItem(random);
    }}
  >
    Scroll to random item
  </button>
);
```

**Comment by haveamission** [comment]
Perfect, worked great, thank you!
