### ISSUE TITLE
Custom dots container not working

### ISSUE THREAD

**Issue by JoalbertMilano** [kevinfarrugia/react-glider#152]
When I try to use a custom dots container using dots props it always uses the default dots container

Changing the validation when initializing the glider works for me, I'm not sure if it's the definitive solution:

![image](https://github.com/kevinfarrugia/react-glider/assets/58334753/6956b0f7-c271-42c0-a0cf-11fa3139776d)

**Comment by kevinfarrugia** [comment]
I created a demo that uses a custom dots container: https://codesandbox.io/s/react-glider-demo-with-dots-qxcd2l

Let me know if that clarifies the issue.

**Comment by JoalbertMilano** [comment]
Applying the dots container as in the demo works perfectly, thank you very much
